spring.main.web-application-type=none
spring.main.banner-mode=off
spring.application.name=projeto_api_1

spring.datasource.url=jdbc:postgresql://localhost:5432/apostas_esportivas
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Desativa todos os logs internos (Spring Boot, HikariCP, Hibernate) para o terminal ficar limpo
logging.level.root=OFF
